// Constants and variables
const localKey = "sllgms-v3";

let savedata = {
    "user": {
        "alreadyPrompted": false,
        "telemetry": false,
        "sex": null,
        "age": null
    },
    "premises": 2,
    "timer": 30,
    "score": 0,
    "enableDistinction": true,
    "enableComparison": true,
    "enableSyllogism": true,
    "enableAnalogy": false,
    "enableDirection": true,
    "enableDirection3D": true,
    "enableDirection4D": true,
    "enableBinary": false,
    "useMeaningfulWords": false,
    "enableCarouselMode": false,
    "enableTemporal": true,
    "enableNegation": true,
    "onlyAnalogy": false,
    "onlyBinary": false,
    "enableMeta": true,
    "maxNestedBinaryDepth": 1,
    "removeNegationExplainer": false,
    "questions": [],
    "nonsenseWordLength": 3,
    "useNonsenseWords": true,
    "useEmoji": false
};

const keySettingMap = {
    "p-1": "enableDistinction",
    "p-2": "enableComparison",
    "p-3": "enableSyllogism",
    "p-4": "enableAnalogy",
    "p-5": "premises",
    "p-6": "enableDirection",
    "p-7": "enableBinary",
    "p-8": "useMeaningfulWords",
    "p-9": "enableCarouselMode",
    "p-10": "enableTemporal",
    "p-11": "enableNegation",
    "p-12": "enableDirection3D",
    "p-13": "enableDirection4D",
    "p-14": "onlyAnalogy",
    "p-15": "onlyBinary",
    "p-16": "enableMeta",
    "p-17": "maxNestedBinaryDepth",
    "p-18": "removeNegationExplainer",
    "p-19": "nonsenseWordLength",
    "p-20": "useNonsenseWords",
    "p-21": "useEmoji"
};

const meaningfulWords = {
    nouns: [
        "ARMOUR",
        "BARRYMORE",
        "CABOT",
        "CATHOLICISM",
        "CHIHUAHUA",
        "CHRISTIANITY",
        "EASTER",
        "FRENCHMAN",
        "LOWRY",
        "MAYER",
        "ORIENTALISM",
        "PHARAOH",
        "PUEBLO",
        "PULLMAN",
        "RODEO",
        "SATURDAY",
        "SISTER",
        "SNEAD",
        "SYRAH",
        "TUESDAY",
        "WOODWARD",
        "ABBEY",
        "ABSENCE",
        "ABSORPTION",
        "ABSTINENCE",
        "ABSURDITY",
        "ABUNDANCE",
        "ACCEPTANCE",
        "ACCESSIBILITY",
        "ACCOMMODATION",
        "ACCOMPLICE",
        "ACCOUNTABILITY",
        "ACCOUNTING",
        "ACCREDITATION",
        "ACCURACY",
        "ACQUIESCENCE",
        "ACREAGE",
        "ACTRESS",
        "ACTUALITY",
        "ADAGE",
        "ADAPTATION",
        "ADHERENCE",
        "ADJUSTMENT",
        "ADOPTION",
        "ADULTERY",
        "ADVANCEMENT",
        "ADVERT",
        "ADVERTISEMENT",
        "ADVERTISING",
        "ADVICE",
        "AESTHETICS",
        "AFFINITY",
        "AGGRESSION",
        "AGRICULTURE",
        "AIRCRAFT",
        "AIRTIME",
        "ALLEGATION",
        "ALLEGIANCE",
        "ALLEGORY",
        "ALLERGY",
        "ALLIES",
        "ALLIGATOR",
        "ALLOCATION",
        "ALLOTMENT",
        "ALTERCATION",
        "AMBULANCE",
        "AMMONIA",
        "ANATOMY",
        "ANEMIA",
        "ANKLE",
        "ANNOUNCEMENT",
        "ANNOYANCE",
        "ANNUITY",
        "ANOMALY",
        "ANTHROPOLOGY",
        "ANXIETY",
        "APARTHEID",
        "APOLOGISE",
        "APOSTLE",
        "APPARATUS",
        "APPEASEMENT",
        "APPELLATION",
        "APPENDIX",
        "APPLAUSE",
        "APPOINTMENT",
        "APPRAISAL",
        "ARCHERY",
        "ARCHIPELAGO",
        "ARCHITECTURE",
        "ARDOR",
        "ARREARS",
        "ARROW",
        "ARTISAN",
        "ARTISTRY",
        "ASCENT",
        "ASSEMBLY",
        "ASSIGNMENT",
        "ASSOCIATION",
        "ASTHMA",
        "ATHEISM",
        "ATTACKER",
        "ATTRACTION",
        "ATTRACTIVENESS",
        "AUSPICES",
        "AUTHORITY",
        "AVARICE",
        "AVERSION",
        "AVIATION",
        "BABBLING",
        "BACKLASH",
        "BAKER",
        "BALLET",
        "BALLS",
        "BANJO",
        "BARON",
        "BARRIER",
        "BARRISTER",
        "BASES",
        "BASIN",
        "BASIS",
        "BATTERY",
        "BATTLING",
        "BEDTIME",
        "BEGINNER",
        "BEGUN",
        "BENDING",
        "BICYCLE",
        "BILLING",
        "BINGO",
        "BIOGRAPHY",
        "BIOLOGY",
        "BIRTHPLACE",
        "BLACKBERRY",
        "BLATHER",
        "BLOSSOM",
        "BOARDROOM",
        "BOASTING",
        "BODYGUARD",
        "BOLDNESS",
        "BOMBER",
        "BONDAGE",
        "BONDING",
        "BONES",
        "BONUS",
        "BOOKMARK",
        "BOOMER",
        "BOOTY",
        "BOUNDS",
        "BOWLING",
        "BRAINSTORMING",
        "BREADTH",
        "BREAKER",
        "BREWER",
        "BRIGHTNESS",
        "BROCCOLI",
        "BROTH",
        "BROTHERHOOD",
        "BROWSING",
        "BRUNCH",
        "BRUNT",
        "BUILDING",
        "BULLION",
        "BUREAUCRACY",
        "BURGLARY",
        "BUYOUT",
        "BY-ELECTION",
        "CABAL",
        "CABBAGE",
        "CALAMITY",
        "CAMPAIGN",
        "CANONIZATION",
        "CAPTAINCY",
        "CARCASS",
        "CARRIER",
        "CARTRIDGE",
        "CASSETTE",
        "CATFISH",
        "CAUGHT",
        "CELEBRITY",
        "CEMETERY",
        "CERTAINTY",
        "CERTIFICATION",
        "CHARADE",
        "CHASM",
        "CHECK-IN",
        "CHEERLEADER",
        "CHEESECAKE",
        "CHEMOTHERAPY",
        "CHILI",
        "CHINA",
        "CHIVALRY",
        "CHOLERA",
        "CILANTRO",
        "CIRCUS",
        "CIVILISATION",
        "CIVILITY",
        "CLEARANCE",
        "CLEARING",
        "CLERK",
        "CLIMBER",
        "CLOSENESS",
        "CLOTHING",
        "CLUTCHES",
        "COASTER",
        "COCONUT",
        "CODING",
        "COLLABORATOR",
        "COLLEAGUE",
        "COLLEGE",
        "COLLISION",
        "COLORS",
        "COMBUSTION",
        "COMEDIAN",
        "COMER",
        "COMMANDER",
        "COMMEMORATION",
        "COMMENTER",
        "COMMISSIONER",
        "COMMUNE",
        "COMPETITION",
        "COMPLETENESS",
        "COMPLEXITY",
        "COMPUTING",
        "COMRADE",
        "CONCUR",
        "CONDOMINIUM",
        "CONDUIT",
        "CONFIDANT",
        "CONFIGURATION",
        "CONFISCATION",
        "CONFLAGRATION",
        "CONFLICT",
        "CONSIST",
        "CONSISTENCY",
        "CONSOLIDATION",
        "CONSPIRACY",
        "CONSTABLE",
        "CONSUL",
        "CONSULTANCY",
        "CONTENTMENT",
        "CONTENTS",
        "CONTRACTOR",
        "CONVERSATION",
        "CORNERSTONE",
        "CORPUS",
        "CORRELATION",
        "COUNCILMAN",
        "COUNSELOR",
        "COUNTDOWN",
        "COUNTRYMAN",
        "COVERAGE",
        "COVERING",
        "COYOTE",
        "CRACKER",
        "CREATOR",
        "CRIMINALITY",
        "CROCODILE",
        "CROPPING",
        "CROSS-EXAMINATION",
        "CROSSOVER",
        "CROSSROADS",
        "CULPRIT",
        "CUMIN",
        "CURATOR",
        "CURFEW",
        "CURSOR",
        "CUSTARD",
        "CUTTER",
        "CYCLIST",
        "CYCLONE",
        "CYLINDER",
        "CYNICISM",
        "DADDY",
        "DAMSEL",
        "DARKNESS",
        "DAWNING",
        "DAYBREAK",
        "DEALING",
        "DEDICATION",
        "DEDUCTION",
        "DEFECTION",
        "DEFERENCE",
        "DEFICIENCY",
        "DEFINITION",
        "DEFLATION",
        "DEGENERATION",
        "DELEGATION",
        "DELICACY",
        "DELIRIUM",
        "DELIVERANCE",
        "DEMEANOR",
        "DEMON",
        "DEMONSTRATION",
        "DENOMINATION",
        "DENTIST",
        "DEPARTURE",
        "DEPLETION",
        "DEPRESSION",
        "DESIGNATION",
        "DESPOTISM",
        "DETENTION",
        "DEVELOPER",
        "DEVOLUTION",
        "DEXTERITY",
        "DIAGNOSIS",
        "DIALECT",
        "DIFFERENTIATION",
        "DIGGER",
        "DIGRESS",
        "DIOXIDE",
        "DIPLOMA",
        "DISABILITY",
        "DISARMAMENT",
        "DISCORD",
        "DISCOVERY",
        "DISHONESTY",
        "DISMISSAL",
        "DISOBEDIENCE",
        "DISPATCHER",
        "DISSERVICE",
        "DISTRIBUTION",
        "DISTRIBUTOR",
        "DIVER",
        "DIVERSITY",
        "DOCKING",
        "DOLLAR",
        "DOMINANCE",
        "DOMINATION",
        "DOMINION",
        "DONKEY",
        "DOORSTEP",
        "DOORWAY",
        "DOSSIER",
        "DOWNSIDE",
        "DRAFTING",
        "DRANK",
        "DRILLING",
        "DRIVER",
        "DRUMMING",
        "DRUNKENNESS",
        "DUCHESS",
        "DUCKING",
        "DUGOUT",
        "DUMPS",
        "DWELLING",
        "DYNAMICS",
        "EAGERNESS",
        "EARNESTNESS",
        "EARNINGS",
        "EATER",
        "EDITOR",
        "EFFECTIVENESS",
        "ELECTRICITY",
        "ELEMENTS",
        "ELOQUENCE",
        "EMANCIPATION",
        "EMBODIMENT",
        "EMBROIDERY",
        "EMPEROR",
        "EMPLOYMENT",
        "ENCAMPMENT",
        "ENCLOSURE",
        "ENCOURAGEMENT",
        "ENDANGERMENT",
        "ENLIGHTENMENT",
        "ENTHUSIASM",
        "ENVIRONMENT",
        "ENVIRONS",
        "ENVOY",
        "EPILEPSY",
        "EQUATION",
        "EQUATOR",
        "ERROR",
        "ESPIONAGE",
        "ESTIMATION",
        "EVACUATION",
        "EXAGGERATION",
        "EXAMINATION",
        "EXCLAMATION",
        "EXPEDIENCY",
        "EXPLOITATION",
        "EXTINCTION",
        "EYEWITNESS",
        "FALLS",
        "FASCISM",
        "FASTBALL",
        "FECES",
        "FEEDBACK",
        "FEROCITY",
        "FERTILIZATION",
        "FETISH",
        "FINALE",
        "FIRING",
        "FIXING",
        "FLASHING",
        "FLASK",
        "FLORA",
        "FLUKE",
        "FOLKLORE",
        "FOLLOWER",
        "FOOTHOLD",
        "FOOTING",
        "FOREFINGER",
        "FOREFRONT",
        "FORGIVENESS",
        "FORMALITY",
        "FORMATION",
        "FORMULA",
        "FOYER",
        "FRAGMENTATION",
        "FRAMEWORK",
        "FRAUD",
        "FREESTYLE",
        "FREQUENCY",
        "FRIENDLINESS",
        "FRIES",
        "FRIGATE",
        "FULFILLMENT",
        "FUNCTION",
        "FUNCTIONALITY",
        "FUNDRAISER",
        "FUSION",
        "FUTILITY",
        "GALLANTRY",
        "GALLERY",
        "GENESIS",
        "GENITALS",
        "GIRLFRIEND",
        "GLAMOUR",
        "GLITTER",
        "GLUCOSE",
        "GOOGLE",
        "GRANDEUR",
        "GRAPPLING",
        "GREENS",
        "GRIDLOCK",
        "GROCER",
        "GROUNDWORK",
        "GROUPING",
        "GUNMAN",
        "GUSTO",
        "HABITATION",
        "HACKER",
        "HALLWAY",
        "HAMBURGER",
        "HAMMOCK",
        "HANDLING",
        "HANDS",
        "HANDSHAKE",
        "HAPPINESS",
        "HARDSHIP",
        "HEADCOUNT",
        "HEADER",
        "HEADQUARTERS",
        "HEADS",
        "HEADSET",
        "HEARTH",
        "HEARTS",
        "HEATH",
        "HEGEMONY",
        "HEIGHT",
        "HELLO",
        "HELPER",
        "HELPING",
        "HELPLESSNESS",
        "HIERARCHY",
        "HOARDING",
        "HOCKEY",
        "HOMELAND",
        "HOMER",
        "HONESTY",
        "HORROR",
        "HORSEMAN",
        "HOSTILITY",
        "HOUSING",
        "HUMILITY",
        "HURRICANE",
        "ICEBERG",
        "IGNITION",
        "ILLNESS",
        "ILLUSTRATION",
        "ILLUSTRATOR",
        "IMMUNITY",
        "IMMUNIZATION",
        "IMPERIALISM",
        "IMPRISONMENT",
        "INACCURACY",
        "INACTION",
        "INACTIVITY",
        "INAUGURATION",
        "INDECENCY",
        "INDICATOR",
        "INEVITABILITY",
        "INFAMY",
        "INFILTRATION",
        "INFLUX",
        "INIQUITY",
        "INNOCENCE",
        "INNOVATION",
        "INSANITY",
        "INSPIRATION",
        "INSTRUCTION",
        "INSTRUCTOR",
        "INSURER",
        "INTERACT",
        "INTERCESSION",
        "INTERCOURSE",
        "INTERMISSION",
        "INTERPRETATION",
        "INTERSECTION",
        "INTERVAL",
        "INTOLERANCE",
        "INTRUDER",
        "INVASION",
        "INVESTMENT",
        "INVOLVEMENT",
        "IRRIGATION",
        "ITERATION",
        "JENNY",
        "JOGGING",
        "JONES",
        "JOSEPH",
        "JUGGERNAUT",
        "JUNCTURE",
        "JURISPRUDENCE",
        "JUROR",
        "KANGAROO",
        "KINGDOM",
        "KNOCKING",
        "LABORER",
        "LARCENY",
        "LAURELS",
        "LAYOUT",
        "LEADERSHIP",
        "LEASING",
        "LEGISLATION",
        "LEOPARD",
        "LIBERATION",
        "LICENCE",
        "LIFEBLOOD",
        "LIFELINE",
        "LIGAMENT",
        "LIGHTING",
        "LIKENESS",
        "LINE-UP",
        "LINEAGE",
        "LINER",
        "LINEUP",
        "LIQUIDATION",
        "LISTENER",
        "LITERATURE",
        "LITIGATION",
        "LITRE",
        "LOATHING",
        "LOCALITY",
        "LODGING",
        "LOGIC",
        "LONGEVITY",
        "LOOKOUT",
        "LORDSHIP",
        "LUSTRE",
        "MA'AM",
        "MACHINERY",
        "MADNESS",
        "MAGNIFICENCE",
        "MAHOGANY",
        "MAILING",
        "MAINFRAME",
        "MAINTENANCE",
        "MAJORITY",
        "MANGA",
        "MANGO",
        "MANIFESTO",
        "MANTRA",
        "MANUFACTURER",
        "MAPLE",
        "MARTIN",
        "MARTYRDOM",
        "MATHEMATICIAN",
        "MATRIX",
        "MATRON",
        "MAYHEM",
        "MAYOR",
        "MEANS",
        "MEANTIME",
        "MEASUREMENT",
        "MECHANICS",
        "MEDIATOR",
        "MEDICS",
        "MELODRAMA",
        "MEMORY",
        "MENTALITY",
        "METAPHYSICS",
        "METHOD",
        "METRE",
        "MINER",
        "MIRTH",
        "MISCONCEPTION",
        "MISERY",
        "MISHAP",
        "MISUNDERSTANDING",
        "MOBILITY",
        "MOLASSES",
        "MOMENTUM",
        "MONARCHY",
        "MONUMENT",
        "MORALE",
        "MORTALITY",
        "MOTTO",
        "MOUTHFUL",
        "MOUTHPIECE",
        "MOVER",
        "MOVIE",
        "MOWING",
        "MURDERER",
        "MUSICIAN",
        "MUTATION",
        "MYTHOLOGY",
        "NARRATION",
        "NARRATOR",
        "NATIONALITY",
        "NEGLIGENCE",
        "NEIGHBORHOOD",
        "NEIGHBOUR",
        "NERVOUSNESS",
        "NETWORKING",
        "NEXUS",
        "NIGHTMARE",
        "NOBILITY",
        "NOBODY",
        "NOODLE",
        "NORMALCY",
        "NOTIFICATION",
        "NOURISHMENT",
        "NOVELLA",
        "NUCLEUS",
        "NUISANCE",
        "NURSERY",
        "NUTRITION",
        "NYLON",
        "OASIS",
        "OBSCENITY",
        "OBSCURITY",
        "OBSERVER",
        "OFFENSE",
        "ONSLAUGHT",
        "OPERATION",
        "OPPORTUNITY",
        "OPPOSITION",
        "ORACLE",
        "ORCHESTRA",
        "ORGANISATION",
        "ORGANIZER",
        "ORIENTATION",
        "ORIGINALITY",
        "OUNCE",
        "OUTAGE",
        "OUTCOME",
        "OUTDOORS",
        "OUTFIELD",
        "OUTING",
        "OUTPOST",
        "OUTSET",
        "OVERSEER",
        "OWNER",
        "OXYGEN",
        "PAIRING",
        "PANTHER",
        "PARADOX",
        "PARLIAMENT",
        "PARSLEY",
        "PARSON",
        "PASSENGER",
        "PASTA",
        "PATCHWORK",
        "PATHOS",
        "PATRIOTISM",
        "PENDULUM",
        "PENGUIN",
        "PERMISSION",
        "PERSONA",
        "PERUSAL",
        "PESSIMISM",
        "PETER",
        "PHILOSOPHER",
        "PHOSPHORUS",
        "PHRASING",
        "PHYSIQUE",
        "PILES",
        "PLATEAU",
        "PLAYING",
        "PLAZA",
        "PLETHORA",
        "PLURALITY",
        "PNEUMONIA",
        "POINTER",
        "POKER",
        "POLICEMAN",
        "POLLING",
        "POSTER",
        "POSTERITY",
        "POSTING",
        "POSTPONEMENT",
        "POTASSIUM",
        "POTTERY",
        "POULTRY",
        "POUNDING",
        "PRAGMATISM",
        "PRECEDENCE",
        "PRECINCT",
        "PREOCCUPATION",
        "PRETENSE",
        "PRIESTHOOD",
        "PRISONER",
        "PRIVACY",
        "PROBATION",
        "PROCEEDING",
        "PROCEEDINGS",
        "PROCESSING",
        "PROCESSOR",
        "PROGRESSION",
        "PROJECTION",
        "PROMINENCE",
        "PROPENSITY",
        "PROPHECY",
        "PROROGATION",
        "PROSPECTUS",
        "PROTEIN",
        "PROTOTYPE",
        "PROVIDENCE",
        "PROVIDER",
        "PROVOCATION",
        "PROXIMITY",
        "PUBERTY",
        "PUBLICIST",
        "PUBLICITY",
        "PUBLISHER",
        "PUNDIT",
        "PUTTING",
        "QUANTITY",
        "QUART",
        "QUILTING",
        "QUORUM",
        "RACISM",
        "RADIANCE",
        "RALPH",
        "RANCHER",
        "RANGER",
        "RAPIDITY",
        "RAPPORT",
        "RATIFICATION",
        "RATIONALITY",
        "REACTION",
        "READER",
        "REASSURANCE",
        "REBIRTH",
        "RECEPTOR",
        "RECIPE",
        "RECOGNITION",
        "RECOURSE",
        "RECREATION",
        "RECTOR",
        "RECURRENCE",
        "REDEMPTION",
        "REDISTRIBUTION",
        "REDUNDANCY",
        "REFINERY",
        "REFORMER",
        "REFRIGERATOR",
        "REGULARITY",
        "REGULATOR",
        "REINFORCEMENT",
        "REINS",
        "REINSTATEMENT",
        "RELATIVISM",
        "RELAXATION",
        "RENDITION",
        "REPAYMENT",
        "REPENTANCE",
        "REPERTOIRE",
        "REPOSITORY",
        "REPUBLIC",
        "REPUTATION",
        "RESENTMENT",
        "RESIDENCY",
        "RESIGNATION",
        "RESTAURANT",
        "RESURGENCE",
        "RETAILER",
        "RETENTION",
        "RETIREMENT",
        "REVIEWER",
        "RICHES",
        "RIGHTEOUSNESS",
        "ROADBLOCK",
        "ROBBER",
        "ROCKS",
        "RUBBING",
        "RUNOFF",
        "SALOON",
        "SALVATION",
        "SARCASM",
        "SAUCER",
        "SAVIOR",
        "SCARCITY",
        "SCENARIO",
        "SCENERY",
        "SCHISM",
        "SCHOLARSHIP",
        "SCHOOLBOY",
        "SCHOONER",
        "SCISSORS",
        "SCOLDING",
        "SCOOTER",
        "SCOURING",
        "SCRIMMAGE",
        "SCRUM",
        "SEATING",
        "SEDIMENT",
        "SEDUCTION",
        "SEEDER",
        "SEIZURE",
        "SELF-CONFIDENCE",
        "SELF-CONTROL",
        "SELF-RESPECT",
        "SEMICOLON",
        "SEMICONDUCTOR",
        "SEMIFINAL",
        "SENATOR",
        "SENDING",
        "SERENITY",
        "SERIOUSNESS",
        "SERVITUDE",
        "SESAME",
        "SETUP",
        "SEWING",
        "SHARPNESS",
        "SHAVING",
        "SHOPLIFTING",
        "SHOPPING",
        "SIDING",
        "SIMPLICITY",
        "SIMULATION",
        "SINKING",
        "SKATE",
        "SLOTH",
        "SLUGGER",
        "SNACK",
        "SNAIL",
        "SNAPSHOT",
        "SNARK",
        "SOCCER",
        "SOLEMNITY",
        "SOLICITATION",
        "SOLITUDE",
        "SOMEWHERE",
        "SOPHISTICATION",
        "SORCERY",
        "SOUVENIR",
        "SPAGHETTI",
        "SPECIFICATION",
        "SPECIMEN",
        "SPECS",
        "SPECTACLE",
        "SPECTRE",
        "SPECULATION",
        "SPERM",
        "SPOILER",
        "SQUAD",
        "SQUID",
        "STAGING",
        "STAGNATION",
        "STAIRCASE",
        "STAIRWAY",
        "STAMINA",
        "STANDPOINT",
        "STANDSTILL",
        "STANZA",
        "STATEMENT",
        "STILLNESS",
        "STIMULUS",
        "STOCKS",
        "STOLE",
        "STOPPAGE",
        "STOREY",
        "STORYTELLER",
        "STYLUS",
        "SUBCOMMITTEE",
        "SUBSCRIPTION",
        "SUBSIDY",
        "SUBURB",
        "SUCCESS",
        "SUFFERER",
        "SUPPOSITION",
        "SUSPENSION",
        "SWEATER",
        "SWEEPSTAKES",
        "SWIMMER",
        "SYNDROME",
        "SYNOPSIS",
        "SYNTAX",
        "SYSTEM",
        "TABLESPOON",
        "TAKER",
        "TAVERN",
        "TECHNOLOGY",
        "TELEPHONY",
        "TEMPLATE",
        "TEMPO",
        "TENDENCY",
        "TENDON",
        "TERRIER",
        "TERROR",
        "TERRY",
        "THEATER",
        "THEOLOGY",
        "THERAPY",
        "THICKET",
        "THOROUGHFARE",
        "THRESHOLD",
        "THRILLER",
        "THUNDERSTORM",
        "TICKER",
        "TIGER",
        "TIGHTS",
        "TO-DAY",
        "TOSSING",
        "TOUCHDOWN",
        "TOURIST",
        "TOURNEY",
        "TOXICITY",
        "TRACING",
        "TRACTOR",
        "TRANSLATION",
        "TRANSMISSION",
        "TRANSMITTER",
        "TRAUMA",
        "TRAVELER",
        "TREADMILL",
        "TRILOGY",
        "TROUT",
        "TUNING",
        "TWENTIES",
        "TYCOON",
        "TYRANT",
        "ULTIMATUM",
        "UNDERDOG",
        "UNDERWEAR",
        "UNHAPPINESS",
        "UNIFICATION",
        "UNIVERSITY",
        "UPRISING",
        "VACCINATION",
        "VALIDITY",
        "VAMPIRE",
        "VANGUARD",
        "VARIATION",
        "VEGETATION",
        "VERIFICATION",
        "VIABILITY",
        "VICINITY",
        "VICTORY",
        "VIEWPOINT",
        "VILLA",
        "VINDICATION",
        "VIOLATION",
        "VISTA",
        "VOCALIST",
        "VOGUE",
        "VOLCANO",
        "VOLTAGE",
        "VOMITING",
        "VULNERABILITY",
        "WAISTCOAT",
        "WAITRESS",
        "WARDROBE",
        "WARMTH",
        "WATCHDOG",
        "WEALTH",
        "WEARINESS",
        "WHEREABOUTS",
        "WHISKY",
        "WHITENESS",
        "WIDGET",
        "WIDTH",
        "WINDFALL",
        "WIRING",
        "WITCHCRAFT",
        "WITHHOLDING",
        "WOMANHOOD",
        "WORDS",
        "WORKMAN",
        "YOUNGSTER"
    ]
}

const emoji = [
    "🀄",
    "🃏",
    "🅰",
    "🅱",
    "🅾",
    "🅿",
    "🆎",
    "🆑",
    "🆒",
    "🆓",
    "🆔",
    "🆕",
    "🆖",
    "🆗",
    "🆘",
    "🆙",
    "🆚",
    "🇦",
    "🇧",
    "🇨",
    "🇩",
    "🇪",
    "🇫",
    "🇬",
    "🇭",
    "🇮",
    "🇯",
    "🇰",
    "🇱",
    "🇲",
    "🇳",
    "🇴",
    "🇵",
    "🇶",
    "🇷",
    "🇸",
    "🇹",
    "🇺",
    "🇻",
    "🇼",
    "🇽",
    "🇾",
    "🇿",
    "🈁",
    "🈂",
    "🈚",
    "🈯",
    "🈲",
    "🈳",
    "🈴",
    "🈵",
    "🈶",
    "🈷",
    "🈸",
    "🈹",
    "🈺",
    "🉐",
    "🉑",
    "🌀",
    "🌁",
    "🌂",
    "🌃",
    "🌄",
    "🌅",
    "🌆",
    "🌇",
    "🌈",
    "🌉",
    "🌊",
    "🌋",
    "🌌",
    "🌍",
    "🌎",
    "🌏",
    "🌐",
    "🌑",
    "🌒",
    "🌓",
    "🌔",
    "🌕",
    "🌖",
    "🌗",
    "🌘",
    "🌙",
    "🌚",
    "🌛",
    "🌜",
    "🌝",
    "🌞",
    "🌟",
    "🌠",
    "🌰",
    "🌱",
    "🌲",
    "🌳",
    "🌴",
    "🌵",
    "🌷",
    "🌸",
    "🌹",
    "🌺",
    "🌻",
    "🌼",
    "🌽",
    "🌾",
    "🌿",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🍄",
    "🍅",
    "🍆",
    "🍇",
    "🍈",
    "🍉",
    "🍊",
    "🍋",
    "🍌",
    "🍍",
    "🍎",
    "🍏",
    "🍐",
    "🍑",
    "🍒",
    "🍓",
    "🍔",
    "🍕",
    "🍖",
    "🍗",
    "🍘",
    "🍙",
    "🍚",
    "🍛",
    "🍜",
    "🍝",
    "🍞",
    "🍟",
    "🍠",
    "🍡",
    "🍢",
    "🍣",
    "🍤",
    "🍥",
    "🍦",
    "🍧",
    "🍨",
    "🍩",
    "🍪",
    "🍫",
    "🍬",
    "🍭",
    "🍮",
    "🍯",
    "🍰",
    "🍱",
    "🍲",
    "🍳",
    "🍴",
    "🍵",
    "🍶",
    "🍷",
    "🍸",
    "🍹",
    "🍺",
    "🍻",
    "🍼",
    "🎀",
    "🎁",
    "🎂",
    "🎃",
    "🎄",
    "🎅",
    "🎆",
    "🎇",
    "🎈",
    "🎉",
    "🎊",
    "🎋",
    "🎌",
    "🎍",
    "🎎",
    "🎏",
    "🎐",
    "🎑",
    "🎒",
    "🎓",
    "🎠",
    "🎡",
    "🎢",
    "🎣",
    "🎤",
    "🎥",
    "🎦",
    "🎧",
    "🎨",
    "🎩",
    "🎪",
    "🎫",
    "🎬",
    "🎭",
    "🎮",
    "🎯",
    "🎰",
    "🎱",
    "🎲",
    "🎳",
    "🎴",
    "🎵",
    "🎶",
    "🎷",
    "🎸",
    "🎹",
    "🎺",
    "🎻",
    "🎼",
    "🎽",
    "🎾",
    "🎿",
    "🏀",
    "🏁",
    "🏂",
    "🏃",
    "🏄",
    "🏆",
    "🏇",
    "🏈",
    "🏉",
    "🏊",
    "🏠",
    "🏡",
    "🏢",
    "🏣",
    "🏤",
    "🏥",
    "🏦",
    "🏧",
    "🏨",
    "🏩",
    "🏪",
    "🏫",
    "🏬",
    "🏭",
    "🏮",
    "🏯",
    "🏰",
    "🐀",
    "🐁",
    "🐂",
    "🐃",
    "🐄",
    "🐅",
    "🐆",
    "🐇",
    "🐈",
    "🐉",
    "🐊",
    "🐋",
    "🐌",
    "🐍",
    "🐎",
    "🐏",
    "🐐",
    "🐑",
    "🐒",
    "🐓",
    "🐔",
    "🐕",
    "🐖",
    "🐗",
    "🐘",
    "🐙",
    "🐚",
    "🐛",
    "🐜",
    "🐝",
    "🐞",
    "🐟",
    "🐠",
    "🐡",
    "🐢",
    "🐣",
    "🐤",
    "🐥",
    "🐦",
    "🐧",
    "🐨",
    "🐩",
    "🐪",
    "🐫",
    "🐬",
    "🐭",
    "🐮",
    "🐯",
    "🐰",
    "🐱",
    "🐲",
    "🐳",
    "🐴",
    "🐵",
    "🐶",
    "🐷",
    "🐸",
    "🐹",
    "🐺",
    "🐻",
    "🐼",
    "🐽",
    "🐾",
    "👀",
    "👂",
    "👃",
    "👄",
    "👅",
    "👆",
    "👇",
    "👈",
    "👉",
    "👊",
    "👋",
    "👌",
    "👍",
    "👎",
    "👏",
    "👐",
    "👑",
    "👒",
    "👓",
    "👔",
    "👕",
    "👖",
    "👗",
    "👘",
    "👙",
    "👚",
    "👛",
    "👜",
    "👝",
    "👞",
    "👟",
    "👠",
    "👡",
    "👢",
    "👣",
    "👤",
    "👥",
    "👦",
    "👧",
    "👨",
    "👩",
    "👪",
    "👫",
    "👬",
    "👭",
    "👮",
    "👯",
    "👰",
    "👱",
    "👲",
    "👳",
    "👴",
    "👵",
    "👶",
    "👷",
    "👸",
    "👹",
    "👺",
    "👻",
    "👼",
    "👽",
    "👾",
    "👿",
    "💀",
    "💁",
    "💂",
    "💃",
    "💄",
    "💅",
    "💆",
    "💇",
    "💈",
    "💉",
    "💊",
    "💋",
    "💌",
    "💍",
    "💎",
    "💏",
    "💐",
    "💑",
    "💒",
    "💓",
    "💔",
    "💕",
    "💖",
    "💗",
    "💘",
    "💙",
    "💚",
    "💛",
    "💜",
    "💝",
    "💞",
    "💟",
    "💠",
    "💡",
    "💢",
    "💣",
    "💤",
    "💥",
    "💦",
    "💧",
    "💨",
    "💩",
    "💪",
    "💫",
    "💬",
    "💭",
    "💮",
    "💯",
    "💰",
    "💱",
    "💲",
    "💳",
    "💴",
    "💵",
    "💶",
    "💷",
    "💸",
    "💹",
    "💺",
    "💻",
    "💼",
    "💽",
    "💾",
    "💿",
    "📀",
    "📁",
    "📂",
    "📃",
    "📄",
    "📅",
    "📆",
    "📇",
    "📈",
    "📉",
    "📊",
    "📋",
    "📌",
    "📍",
    "📎",
    "📏",
    "📐",
    "📑",
    "📒",
    "📓",
    "📔",
    "📕",
    "📖",
    "📗",
    "📘",
    "📙",
    "📚",
    "📛",
    "📜",
    "📝",
    "📞",
    "📟",
    "📠",
    "📡",
    "📢",
    "📣",
    "📤",
    "📥",
    "📦",
    "📧",
    "📨",
    "📩",
    "📪",
    "📫",
    "📬",
    "📭",
    "📮",
    "📯",
    "📰",
    "📱",
    "📲",
    "📳",
    "📴",
    "📵",
    "📶",
    "📷",
    "📹",
    "📺",
    "📻",
    "📼",
    "🔀",
    "🔁",
    "🔂",
    "🔃",
    "🔄",
    "🔅",
    "🔆",
    "🔇",
    "🔈",
    "🔉",
    "🔊",
    "🔋",
    "🔌",
    "🔍",
    "🔎",
    "🔏",
    "🔐",
    "🔑",
    "🔒",
    "🔓",
    "🔔",
    "🔕",
    "🔖",
    "🔗",
    "🔘",
    "🔙",
    "🔚",
    "🔛",
    "🔜",
    "🔝",
    "🔞",
    "🔟",
    "🔠",
    "🔡",
    "🔢",
    "🔣",
    "🔤",
    "🔥",
    "🔦",
    "🔧",
    "🔨",
    "🔩",
    "🔪",
    "🔫",
    "🔬",
    "🔭",
    "🔮",
    "🔯",
    "🔰",
    "🔱",
    "🔲",
    "🔳",
    "🔴",
    "🔵",
    "🔶",
    "🔷",
    "🔸",
    "🔹",
    "🔺",
    "🔻",
    "🔼",
    "🔽",
    "🕐",
    "🕑",
    "🕒",
    "🕓",
    "🕔",
    "🕕",
    "🕖",
    "🕗",
    "🕘",
    "🕙",
    "🕚",
    "🕛",
    "🕜",
    "🕝",
    "🕞",
    "🕟",
    "🕠",
    "🕡",
    "🕢",
    "🕣",
    "🕤",
    "🕥",
    "🕦",
    "🕧",
    "🗻",
    "🗼",
    "🗽",
    "🗾",
    "🗿",
    "😀",
    "😁",
    "😂",
    "😃",
    "😄",
    "😅",
    "😆",
    "😇",
    "😈",
    "😉",
    "😊",
    "😋",
    "😌",
    "😍",
    "😎",
    "😏",
    "😐",
    "😑",
    "😒",
    "😓",
    "😔",
    "😕",
    "😖",
    "😗",
    "😘",
    "😙",
    "😚",
    "😛",
    "😜",
    "😝",
    "😞",
    "😟",
    "😠",
    "😡",
    "😢",
    "😣",
    "😤",
    "😥",
    "😦",
    "😧",
    "😨",
    "😩",
    "😪",
    "😫",
    "😬",
    "😭",
    "😮",
    "😯",
    "😰",
    "😱",
    "😲",
    "😳",
    "😴",
    "😵",
    "😶",
    "😷",
    "😸",
    "😹",
    "😺",
    "😻",
    "😼",
    "😽",
    "😾",
    "😿",
    "🙀",
    "🙁",
    "🙂",
    "🙅",
    "🙆",
    "🙇",
    "🙈",
    "🙉",
    "🙊",
    "🙋",
    "🙌",
    "🙍",
    "🙎",
    "🙏",
    "🚀",
    "🚁",
    "🚂",
    "🚃",
    "🚄",
    "🚅",
    "🚆",
    "🚇",
    "🚈",
    "🚉",
    "🚊",
    "🚋",
    "🚌",
    "🚍",
    "🚎",
    "🚏",
    "🚐",
    "🚑",
    "🚒",
    "🚓",
    "🚔",
    "🚕",
    "🚖",
    "🚗",
    "🚘",
    "🚙",
    "🚚",
    "🚛",
    "🚜",
    "🚝",
    "🚞",
    "🚟",
    "🚠",
    "🚡",
    "🚢",
    "🚣",
    "🚤",
    "🚥",
    "🚦",
    "🚧",
    "🚨",
    "🚩",
    "🚪",
    "🚫",
    "🚬",
    "🚭",
    "🚮",
    "🚯",
    "🚰",
    "🚱",
    "🚲",
    "🚳",
    "🚴",
    "🚵",
    "🚶",
    "🚷",
    "🚸",
    "🚹",
    "🚺",
    "🚻",
    "🚼",
    "🚽",
    "🚾",
    "🚿",
    "🛀",
    "🛁",
    "🛂",
    "🛃",
    "🛄",
    "🛅",
    "‼",
    "⁉",
    "™",
    "ℹ",
    "↔",
    "↕",
    "↖",
    "↗",
    "↘",
    "↙",
    "↩",
    "↪",
    "#",
    "⌚",
    "⌛",
    "⏩",
    "⏪",
    "⏫",
    "⏬",
    "⏰",
    "⏳",
    "Ⓜ",
    "▪",
    "▫",
    "▶",
    "◀",
    "◻",
    "◼",
    "◽",
    "◾",
    "☀",
    "☁",
    "☎",
    "☑",
    "☔",
    "☕",
    "☝",
    "☺",
    "♈",
    "♉",
    "♊",
    "♋",
    "♌",
    "♍",
    "♎",
    "♏",
    "♐",
    "♑",
    "♒",
    "♓",
    "♠",
    "♣",
    "♥",
    "♦",
    "♨",
    "♻",
    "♿",
    "⚓",
    "⚠",
    "⚡",
    "⚪",
    "⚫",
    "⚽",
    "⚾",
    "⛄",
    "⛅",
    "⛎",
    "⛔",
    "⛪",
    "⛲",
    "⛳",
    "⛵",
    "⛺",
    "⛽",
    "✂",
    "✅",
    "✈",
    "✉",
    "✊",
    "✋",
    "✌",
    "✏",
    "✒",
    "✔",
    "✖",
    "✨",
    "✳",
    "✴",
    "❄",
    "❇",
    "❌",
    "❎",
    "❓",
    "❔",
    "❕",
    "❗",
    "❤",
    "➕",
    "➖",
    "➗",
    "➡",
    "➰",
    "➿",
    "⤴",
    "⤵",
    "⬅",
    "⬆",
    "⬇",
    "⬛",
    "⬜",
    "⭐",
    "⭕",
    "0",
    "〰",
    "〽",
    "1",
    "2",
    "㊗",
    "㊙",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "©",
    "®",
    ""
]

const validRules = [
    "0001",
    "1011",
    "0221",
    "1231",
    "0021",
    "1031",
    "0112",
    "1012",
    "1232",
    "0332",
    "0132",
    "1032",
    "0223",
    "2023",
    "3033",
    "1233",
    "0023",
    "1033",
    "0114",
    "2024",
    "1234",
    "0134",
    "1034",
    "0024"
];

// This seems such a stupid idea but it opens the possibility of variants
const forms = [
    [
        'All <span class="subject">$</span> is <span class="subject">$</span>',
        'No <span class="subject">$</span> is <span class="subject">$</span>',
        'Some <span class="subject">$</span> is <span class="subject">$</span>',
        'Some <span class="subject">$</span> is not <span class="subject">$</span>'
    ],
    [
        '<span class="is-negated">No</span> <span class="subject">$</span> is <span class="subject">$</span>',
        '<span class="is-negated">All</span> <span class="subject">$</span> is <span class="subject">$</span>',
        'Some <span class="subject">$</span> <span class="is-negated">is not</span> <span class="subject">$</span>',
        'Some <span class="subject">$</span> <span class="is-negated">is</span> <span class="subject">$</span>'
    ],
];

const dirNames = [
    null,
    "North",
    "North-East",
    "East",
    "South-East",
    "South",
    "South-West",
    "West",
    "North-West"
];

const nameInverseDir = {
    "North": "South",
    "North-East": "South-West",
    "East": "West",
    "South-East": "North-West",
    "South": "North",
    "South-West": "North-East",
    "West": "East",
    "North-West": "South-East"
};

const dirCoords = [
    [ 0,  0],
    [ 0, -1],
    [ 1, -1],
    [ 1,  0],
    [ 1,  1],
    [ 0,  1],
    [-1,  1],
    [-1,  0],
    [-1, -1]
];

const dirString = (x, y, z) => {
    let str = '';
    if (z === 1) str = 'Above';
    if (z === -1) str = 'Below';
    if (z && (x || y)) str += ' and ';
    if (y === 1) str += 'North';
    if (y === -1) str += 'South';
    if (y && x) str += '-';
    if (x === 1) str += 'East';
    if (x === -1) str += 'West';
    return str;
}

const dirCoords3D = [];
const dirNames3D = [];
const nameInverseDir3D = {};

const xs = Array(3).fill(0).map((_, i) => i-1)
xs.map(x =>
    xs.map(y =>
        xs.map(z => {
            if (x === 0 && y === 0 && z === 0) return;
            dirCoords3D.push([ x, y, z ]);
            dirNames3D.push(dirString(x, y, z));
            nameInverseDir3D[dirString(x, y, z)] = dirString(-x, -y, -z);
        })
    )
);

const timeNames = ['was', 'is', 'will be'];

const paradoxes = [
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "The sentence that follows is true",
            "The sentence before is false"
        ],
        conclusion: "Is the former sentence true?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "Nothing is better than eternal bliss",
            "And a slice of bread is better than nothing"
        ],
        conclusion: "So is a slice of bread better than eternal bliss?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "Nobody goes to that restaurant",
            "It is too crowded"
        ],
        conclusion: "So did anyone go to that restaurant?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "Don't go near the water",
            "Until you learned how to swim"
        ],
        conclusion: "Can you?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "The man who wrote such a stupid question can not write at all"
        ],
        conclusion: "Could he?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "There's a bullet which can shoot through any barrier",
            "There's also an absolutely bullet-proof armor which no object can penetrate"
        ],
        conclusion: "Can such a bullet penetrate such an armor?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "A man drown in the fountain of eternal life"
        ],
        conclusion: "Could he?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "Your mission is not to accept the mission"
        ],
        conclusion: "Do you accept?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "A girl goes into the past and kills her Grandma",
            "Since her Grandma is dead, the girl was never born"
        ],
        conclusion: "If she was never born, then could she kill her grandma?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "The temperature this morning is 0 degrees",
            "And the weather channel says that it will be twice as cold tomorrow"
        ],
        conclusion: "Will it be colder?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "Answer truthfully to the following question:"
        ],
        conclusion: "Will the next button you press be 'false'?"
    },
    {
        category: "Paradox",
        isValid: "undeterminate",
        premises: [
            "If the God Almighty creates a stone, which he is not capable of lifting"
        ],
        conclusion: "Will he be able to lift it?"
    }
];

const logicPuzzles = [
    {
        category: "Logic",
        isValid: false,
        premises: [
            "There are three fellows",
            "You ask the to first: Are you a Swindlecant?",
            "The answer is not comprehensible",
            "So you ask to the second: What did the first fellow say?",
            "The second fellow says: my other fellow said that he is a Swindlecant",
            "And to that the last fellow says: Do not believe him, he is lying!",
            "Honestants always speak the truth",
            "Swindlecants always lie"
        ],
        conclusion: "Is the second fellow a Honestant?"
    },
    {
        category: "Logic",
        isValid: true,
        premises: [
            "Honestants always speak the truth",
            "Swindlecants always lie",
            "There are two fellows",
            "A fellow says: I'm a Swindlecant or the other one is an Honestant",
        ],
        conclusion: "Is he an Honestant?"
    },
    {
        category: "Logic",
        isValid: true,
        premises: [
            "You are condemned to death",
            "But there's a chance to save yourself",
            "There are 2 doors, one is death and the other is freedom",
            "These doors are guarded by 2 guards",
            "And only them know which door leads to freedom",
            "You can ask one question to one guard",
            "And you know that one guard always lie"
        ],
        conclusion: "Is there a question that can save you? (if so which one?)"
    },
    {
        category: "Logic",
        isValid: false,
        premises: [
            "There are two fellows",
            "A fellow says: We are all Swindlecants",
            "Another fellow concludes: Just one of us is an Honestant",
            "Honestants always speak the truth",
            "Swindlecants always lie"
        ],
        conclusion: "Is the one who has not spoken an Honestant?"
    },
    {
        category: "Logic",
        isValid: true,
        premises: [
            "Honestants always speak the truth",
            "Swindlecants always lie",
            "A guys says: If my wife is an Honestant, then I am a Swindlecant"
        ],
        conclusion: "Is the guy an Honestant? (what about the wife?)"
    },
    {
        category: "Logic",
        isValid: "undeterminate",
        premises: [
            "You are about to pay the check at the restaurant",
            "The cashier tell you how much you owe, and you find it quite expensive",
            "So you ask if he spoke the truth",
            "But you couldn't hear the answer so you ask a man next to you about it",
            "The man says: The cashier said yes, but he is a big liar"
        ],
        conclusion: "Is the cashier lying?"
    },
    {
        category: "Logic",
        isValid: true,
        premises: [
            "You heard about a buried treasure",
            "So you ask another man and he says:",
            "On this island there is a treasure only if I'm an Honestant",
            "Honestants always speak the truth",
            "Swindlecants always lie"
        ],
        conclusion: "Should you go and find the treasure?"
    },
    {
        category: "Logic",
        isValid: true,
        premises: [
            "Honestants always speak the truth",
            "Swindlecants always lie",
            "You forgot what day is",
            "So you ask 4 aborigines:",
            "A: Yesterday was Wednesday",
            "B: Tomorrow will be Sunday",
            "C: Today is Friday",
            "D: The day before yesterday was Thursday"
        ],
        conclusion: "Is D telling the truth? (what day is?)"
    },
    {
        category: "Logic",
        isValid: false,
        premises: [
            "Two people want to talk with you",
            "And you ask: Is at least one of you an Honestant?",
            "After the answers there was no doubt",
            "Honestants always speak the truth",
            "Swindlecants always lie"
        ],
        conclusion: "Are they both liers? (who are they?)"
    },
    {
        category: "Logic",
        isValid: true,
        premises: [
            "Honestants always speak the truth",
            "Swindlecants always lie",
            "There was a girl that everybody wanted to marry",
            "But she only want to marry a rich Swindlecant"
        ],
        conclusion: "Is there a sentence that would convince her? (if so which one?)"
    }
]; // TODO add more (#11)