import { ISettings } from "../models/settings.models";
import { EnumTiers } from "../models/syllogimous.models";

// TODO: Make a map with color for each tier

export const TIER_SETTINGS_MAP: Record<EnumTiers, ISettings> = {
    [EnumTiers.Adept]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Savant]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Mastermind]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Visionary]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Genius]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Luminary]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Prodigy]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Oracle]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Sage]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Philosopher]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Mystic]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Transcendent]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true, // Enabled
        enableComparisonNumerical: false,
        enableComparisonChronological: false,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,
        
        enableAnd: false,
        enableNand: false,
        enableOr: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    }
}