import { ISettings } from "../models/settings.models";
import { EnumTiers } from "../models/syllogimous.models";

export const TIER_COLORS: Record<string, {bgColor: string, textColor: string}> = {
    [EnumTiers.Adept]: { bgColor: "#F0F8FF", textColor: "#045D56" },  // Alice Blue with Teal
    [EnumTiers.Savant]: { bgColor: "#E6E6FA", textColor: "#4B0082" },  // Lavender with Indigo
    [EnumTiers.Mastermind]: { bgColor: "#DDA0DD", textColor: "#483D8B" },  // Plum with Dark Slate Blue
    [EnumTiers.Visionary]: { bgColor: "#B0E0E6", textColor: "#002366" },  // Powder Blue with Royal Blue
    [EnumTiers.Genius]: { bgColor: "#AFEEEE", textColor: "#004953" },  // Pale Turquoise with Deep Aqua
    [EnumTiers.Luminary]: { bgColor: "#98FB98", textColor: "#006400" },  // Pale Green with Dark Green
    [EnumTiers.Prodigy]: { bgColor: "#FFFACD", textColor: "#556B2F" },  // Lemon Chiffon with Dark Olive Green
    [EnumTiers.Oracle]: { bgColor: "#FFDAB9", textColor: "#A0522D" },  // Peach Puff with Sienna
    [EnumTiers.Sage]: { bgColor: "#FFC0CB", textColor: "#8B0000" },  // Pink with Dark Red
    [EnumTiers.Philosopher]: { bgColor: "#D8BFD8", textColor: "#4A235A" },  // Thistle with Dark Purple
    [EnumTiers.Mystic]: { bgColor: "#C71585", textColor: "#FFE4E1" },  // Medium Violet Red with Misty Rose
    [EnumTiers.Transcendent]: { bgColor: "#4B0082", textColor: "#F0F8FF" }   // Indigo with Alice Blue
};

export const TIER_SCORE_RANGES: Record<string, { minScore: number, maxScore: number }> = {
    [EnumTiers.Adept]: { minScore: -Infinity, maxScore: 99 },
    [EnumTiers.Savant]: { minScore: 100, maxScore: 249 },
    [EnumTiers.Mastermind]: { minScore: 250, maxScore: 549 },
    [EnumTiers.Visionary]: { minScore: 550, maxScore: 999 },
    [EnumTiers.Genius]: { minScore: 1000, maxScore: 1599 },
    [EnumTiers.Luminary]: { minScore: 1600, maxScore: 2399 },
    [EnumTiers.Prodigy]: { minScore: 2400, maxScore: 3399 },
    [EnumTiers.Oracle]: { minScore: 3400, maxScore: 4599 },
    [EnumTiers.Sage]: { minScore: 4600, maxScore: 5999 },
    [EnumTiers.Philosopher]: { minScore: 6000, maxScore: 7599 },
    [EnumTiers.Mystic]: { minScore: 7600, maxScore: 9399 },
    [EnumTiers.Transcendent]: { minScore: 9400, maxScore: Infinity }
};

export const TIER_SCORE_ADJUSTMENTS: Record<string, { increment: number, decrement: number }> = {
    [EnumTiers.Adept]: { increment: 10, decrement: 5 },
    [EnumTiers.Savant]: { increment: 10, decrement: 5 },
    [EnumTiers.Mastermind]: { increment: 10, decrement: 5 },
    [EnumTiers.Visionary]: { increment: 10, decrement: 5 },
    [EnumTiers.Genius]: { increment: 10, decrement: 5 },
    [EnumTiers.Luminary]: { increment: 10, decrement: 5 },
    [EnumTiers.Prodigy]: { increment: 5, decrement: 5 },
    [EnumTiers.Oracle]: { increment: 5, decrement: 5 },
    [EnumTiers.Sage]: { increment: 5, decrement: 5 },
    [EnumTiers.Philosopher]: { increment: 5, decrement: 5 },
    [EnumTiers.Mystic]: { increment: 5, decrement: 5 },
    [EnumTiers.Transcendent]: { increment: 5, decrement: 5 }
};

export const TIER_SETTINGS: Record<EnumTiers, ISettings> = {
    [EnumTiers.Adept]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: false,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: false,
        enableDirection: false,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,

        enableAnd: false,
        enableOr: false,
        enableNand: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 90,
        timerComparisonNumerical: 90,
        timerComparisonChronological: 90,
        timerSyllogism: 90,
        timerDirection: 90,
        timerDirection3D: 90,
        timerDirection4D: 90,
        timerAnalogy: 90,
        timerBinary: 90,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Savant]: {
        enableMeaningfulWords: true,
        enableNegation: false,
        enableMeta: true,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: false,
        enableDirection: true,
        enableDirection3D: false,
        enableDirection4D: false,
        enableAnalogy: false,
        enableBinary: false,

        enableAnd: false,
        enableOr: false,
        enableNand: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 75,
        timerComparisonNumerical: 75,
        timerComparisonChronological: 75,
        timerSyllogism: 75,
        timerDirection: 75,
        timerDirection3D: 75,
        timerDirection4D: 75,
        timerAnalogy: 75,
        timerBinary: 75,

        premisesDistinction: 2,
        premisesComparisonNumerical: 2,
        premisesComparisonChronological: 2,
        premisesSyllogism: 2,
        premisesDirection: 2,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Mastermind]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: true,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: false,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: false,
        enableNor: false,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 60,
        timerComparisonNumerical: 60,
        timerComparisonChronological: 60,
        timerSyllogism: 60,
        timerDirection: 60,
        timerDirection3D: 60,
        timerDirection4D: 60,
        timerAnalogy: 60,
        timerBinary: 60,

        premisesDistinction: 3,
        premisesComparisonNumerical: 3,
        premisesComparisonChronological: 3,
        premisesSyllogism: 2,
        premisesDirection: 3,
        premisesDirection3D: 2,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Visionary]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: false,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: true,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: true,
        enableNor: true,
        enableXor: false,
        enableXnor: false,

        timerDistinction: 55,
        timerComparisonNumerical: 55,
        timerComparisonChronological: 55,
        timerSyllogism: 55,
        timerDirection: 55,
        timerDirection3D: 55,
        timerDirection4D: 55,
        timerAnalogy: 55,
        timerBinary: 55,

        premisesDistinction: 3,
        premisesComparisonNumerical: 3,
        premisesComparisonChronological: 3,
        premisesSyllogism: 3,
        premisesDirection: 3,
        premisesDirection3D: 3,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Genius]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: false,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: true,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: true,
        enableNor: true,
        enableXor: true,
        enableXnor: true,

        timerDistinction: 50,
        timerComparisonNumerical: 50,
        timerComparisonChronological: 50,
        timerSyllogism: 50,
        timerDirection: 50,
        timerDirection3D: 50,
        timerDirection4D: 50,
        timerAnalogy: 50,
        timerBinary: 50,

        premisesDistinction: 4,
        premisesComparisonNumerical: 4,
        premisesComparisonChronological: 3,
        premisesSyllogism: 3,
        premisesDirection: 4,
        premisesDirection3D: 3,
        premisesDirection4D: 2,
        premisesAnalogy: 3,
        premisesBinary: 4,
    },
    [EnumTiers.Luminary]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: false,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: true,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: true,
        enableNor: true,
        enableXor: true,
        enableXnor: true,

        timerDistinction: 45,
        timerComparisonNumerical: 45,
        timerComparisonChronological: 45,
        timerSyllogism: 45,
        timerDirection: 45,
        timerDirection3D: 45,
        timerDirection4D: 45,
        timerAnalogy: 45,
        timerBinary: 45,

        premisesDistinction: 5,
        premisesComparisonNumerical: 4,
        premisesComparisonChronological: 4,
        premisesSyllogism: 4,
        premisesDirection: 5,
        premisesDirection3D: 4,
        premisesDirection4D: 3,
        premisesAnalogy: 4,
        premisesBinary: 5,
    },
    [EnumTiers.Prodigy]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: true,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: true,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: true,
        enableNor: true,
        enableXor: true,
        enableXnor: true,

        timerDistinction: 40,
        timerComparisonNumerical: 40,
        timerComparisonChronological: 40,
        timerSyllogism: 40,
        timerDirection: 40,
        timerDirection3D: 40,
        timerDirection4D: 40,
        timerAnalogy: 40,
        timerBinary: 40,

        premisesDistinction: 6,
        premisesComparisonNumerical: 5,
        premisesComparisonChronological: 5,
        premisesSyllogism: 5,
        premisesDirection: 6,
        premisesDirection3D: 5,
        premisesDirection4D: 4,
        premisesAnalogy: 4,
        premisesBinary: 5,
    },
    [EnumTiers.Oracle]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: true,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: true,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: true,
        enableNor: true,
        enableXor: true,
        enableXnor: true,

        timerDistinction: 35,
        timerComparisonNumerical: 35,
        timerComparisonChronological: 35,
        timerSyllogism: 35,
        timerDirection: 35,
        timerDirection3D: 35,
        timerDirection4D: 35,
        timerAnalogy: 35,
        timerBinary: 35,

        premisesDistinction: 7,
        premisesComparisonNumerical: 6,
        premisesComparisonChronological: 6,
        premisesSyllogism: 6,
        premisesDirection: 7,
        premisesDirection3D: 6,
        premisesDirection4D: 5,
        premisesAnalogy: 5,
        premisesBinary: 6,
    },
    [EnumTiers.Sage]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: true,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: true,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: true,
        enableNor: true,
        enableXor: true,
        enableXnor: true,

        timerDistinction: 30,
        timerComparisonNumerical: 30,
        timerComparisonChronological: 30,
        timerSyllogism: 30,
        timerDirection: 30,
        timerDirection3D: 30,
        timerDirection4D: 30,
        timerAnalogy: 30,
        timerBinary: 30,

        premisesDistinction: 8,
        premisesComparisonNumerical: 7,
        premisesComparisonChronological: 7,
        premisesSyllogism: 7,
        premisesDirection: 8,
        premisesDirection3D: 7,
        premisesDirection4D: 6,
        premisesAnalogy: 6,
        premisesBinary: 7,
    },
    [EnumTiers.Philosopher]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: true,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: true,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: true,
        enableNor: true,
        enableXor: true,
        enableXnor: true,

        timerDistinction: 25,
        timerComparisonNumerical: 25,
        timerComparisonChronological: 25,
        timerSyllogism: 25,
        timerDirection: 25,
        timerDirection3D: 25,
        timerDirection4D: 25,
        timerAnalogy: 25,
        timerBinary: 25,

        premisesDistinction: 9,
        premisesComparisonNumerical: 8,
        premisesComparisonChronological: 8,
        premisesSyllogism: 8,
        premisesDirection: 9,
        premisesDirection3D: 8,
        premisesDirection4D: 7,
        premisesAnalogy: 7,
        premisesBinary: 8,
    },
    [EnumTiers.Mystic]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: true,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: true,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: true,
        enableNor: true,
        enableXor: true,
        enableXnor: true,

        timerDistinction: 20,
        timerComparisonNumerical: 20,
        timerComparisonChronological: 20,
        timerSyllogism: 20,
        timerDirection: 20,
        timerDirection3D: 20,
        timerDirection4D: 20,
        timerAnalogy: 20,
        timerBinary: 20,

        premisesDistinction: 10,
        premisesComparisonNumerical: 9,
        premisesComparisonChronological: 9,
        premisesSyllogism: 9,
        premisesDirection: 10,
        premisesDirection3D: 9,
        premisesDirection4D: 8,
        premisesAnalogy: 8,
        premisesBinary: 9,
    },
    [EnumTiers.Transcendent]: {
        enableMeaningfulWords: true,
        enableNegation: true,
        enableMeta: true,

        enableDistinction: true,
        enableComparisonNumerical: true,
        enableComparisonChronological: true,
        enableSyllogism: true,
        enableDirection: true,
        enableDirection3D: true,
        enableDirection4D: true,
        enableAnalogy: true,
        enableBinary: true,

        enableAnd: true,
        enableOr: true,
        enableNand: true,
        enableNor: true,
        enableXor: true,
        enableXnor: true,

        timerDistinction: 15,
        timerComparisonNumerical: 15,
        timerComparisonChronological: 15,
        timerSyllogism: 15,
        timerDirection: 15,
        timerDirection3D: 15,
        timerDirection4D: 15,
        timerAnalogy: 15,
        timerBinary: 15,

        premisesDistinction: 12,
        premisesComparisonNumerical: 10,
        premisesComparisonChronological: 10,
        premisesSyllogism: 10,
        premisesDirection: 12,
        premisesDirection3D: 10,
        premisesDirection4D: 9,
        premisesAnalogy: 9,
        premisesBinary: 10,
    }
}