export const flavorList = [
    { id: 0, name: "Acai Berry" },
    { id: 1, name: "Alaskan Mint" },
    { id: 2, name: "Almond Chocolate Coconut" },
    { id: 3, name: "Amaretto Brownie" },
    { id: 4, name: "Amaretto Cherry" },
    { id: 5, name: "Apple Cinnamon" },
    { id: 6, name: "Banana" },
    { id: 7, name: "Bittersweet Mint" },
    { id: 8, name: "Black Raspberry Crunch" },
    { id: 9, name: "Blueberry" },
    { id: 10, name: "Brown Butter" },
    { id: 11, name: "Brown Sugar Cinnamon" },
    { id: 12, name: "Bubblegum" },
    { id: 13, name: "Bumbleberry" },
    { id: 14, name: "Butter Pecan" },
    { id: 15, name: "California Caramel" },
    { id: 16, name: "Cappuccino" },
    { id: 17, name: "Caramel Toffee Crunch" },
    { id: 18, name: "Cherry" },
    { id: 19, name: "Chocolate" },
    { id: 20, name: "Cinnamon" },
    { id: 21, name: "Coconut" },
    { id: 22, name: "Coffee & Toffee" },
    { id: 23, name: "Confetti" },
    { id: 24, name: "Cookie Dough" },
    { id: 25, name: "Crunchy Grasshopper" },
    { id: 26, name: "Deluxe Strawberry Surf" },
    { id: 27, name: "Grape" },
    { id: 28, name: "Hazelnut" },
    { id: 29, name: "Honey Cinnamon" },
    { id: 30, name: "Irish Cream" },
    { id: 31, name: "Licorice" },
    { id: 32, name: "Mocha Latté" },
    { id: 33, name: "Paradise" },
    { id: 34, name: "Peach" },
    { id: 35, name: "Pistachio" },
    { id: 36, name: "Strawberry" },
    { id: 37, name: "Sweet Potato with Torched Marshmallows" },
    { id: 38, name: "Teaberry" },
    { id: 39, name: "Tiramisu" }
];